# Generated by Django 5.0.6 on 2024-10-01 00:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_setting"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Setting",
        ),
    ]
