# Generated by Django 5.0.6 on 2024-12-06 00:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0004_setting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menu",
            name="items",
        ),
        migrations.RemoveField(
            model_name="menu",
            name="permissions",
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="permissions",
        ),
        migrations.RemoveField(
            model_name="message",
            name="receiver",
        ),
        migrations.RemoveField(
            model_name="message",
            name="sender",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="message",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="user",
        ),
        migrations.RemoveField(
            model_name="setting",
            name="content_type",
        ),
        migrations.DeleteModel(
            name="DashboardLayout",
        ),
        migrations.DeleteModel(
            name="Menu",
        ),
        migrations.DeleteModel(
            name="MenuItem",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
        migrations.DeleteModel(
            name="Setting",
        ),
    ]
